import {
    Activity,
    AlertTriangle,
    ArrowRight,
    BadgeCheck,
    Banknote,
    BookOpen,
    CalendarIcon,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    Construction,
    CreditCard,
    File,
    FileText,
    HelpCircle,
    Image,
    Laptop,
    Loader2,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Search,
    Settings,
    SunMedium,
    Trash,
    Twitter,
    User,
    X,
    PackageSearch,
    LucideIcon,
    Trash2,
    ImagePlus,
    MenuIcon,
    ClipboardCheckIcon,
    MailCheck,
    TabletSmartphone,
    MapPin,
    Landmark,
    Info,
    Linkedin,
    Facebook,
    CircleDollarSign,
    ShieldCheck,
    ShieldX,
    Tractor,
    FileLineChart
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
    command: Command,
    logo: Activity,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    twitter: Twitter,
    check: Check,
    construction: Construction,
    badgeCheck: BadgeCheck,
    search: Search,
    calender: CalendarIcon,
    productSearch: PackageSearch,
    bin: Trash2,
    image: ImagePlus,
    menu: MenuIcon,
    dollar: Banknote,
    clipboardCheck: ClipboardCheckIcon,
    mail: MailCheck,
    phone: TabletSmartphone,
    map: MapPin,
    landmark: Landmark,
    info: Info,
    linkedin: Linkedin,
    facebook: Facebook,
    circleDollarSign: CircleDollarSign,
    verified: ShieldCheck,
    unverified: ShieldX,
    tractor: Tractor,
    lineChart: FileLineChart,
    bookOpen: BookOpen
}
