import {
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  CalendarIcon,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  Construction,
  CreditCard,
  File,
  FileText,
  FileSpreadsheet,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Search,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  PackageSearch,
  LucideIcon,
  Trash2,
  ImagePlus,
  Tractor,
  Package,
  CheckCircle2,
  CheckCircle,
  Circle,
  AlertCircle,
  Sparkles,
  Zap,
  Info,
  Beef,
  Rabbit,
  Bird,
  PiggyBank,
  UtensilsCrossed,
  Upload,
  Pencil,
  Tag,
  ClipboardList,
  Beaker
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  loader: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  alertTriangle: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  construction: Construction,
  badgeCheck: BadgeCheck,
  search: Search,
  calender: CalendarIcon,
  productSearch: PackageSearch,
  bin: Trash2,
  image: ImagePlus,
  tractor: Tractor,
  package: Package,
  checkCircle2: CheckCircle2,
  checkCircle: CheckCircle,
  circle: Circle,
  alertCircle: AlertCircle,
  sparkles: Sparkles,
  zap: Zap,
  info: Info,
  beef: Beef,
  rabbit: Rabbit,
  bird: Bird,
  piggyBank: PiggyBank,
  utensilsCrossed: UtensilsCrossed,
  fileSpreadsheet: FileSpreadsheet,
  upload: Upload,
  edit: Pencil,
  tag: Tag,
  clipboardList: ClipboardList,
  beaker: Beaker
}
